### ISSUE TITLE
Are you accepting pull requests for this?

### ISSUE THREAD

**Issue by JakeBartolin** [espy02/python-minesweeper#1]
My name's Jake. I'm currently working on teching myself Python and I'm looking for some code to read through and practice my refactoring skills. Would you mind if I made a couple pull requests to this? The program itsself seems super cool (never seen someone create minesweeper in a terminal). I have a couple ideas that might make this a bit cleaner and was wondering if you were accepting PRs?

**Comment by espy02** [comment]
Hi Jake, sorry for taking so long to respond.
I'm not entirely sure what a pull request it, but if I'm understanding it correctly, it's a way for you to request changes to my code.
This is a personal project, so I would prefer if every piece of code was written by me. As my programming skills evolve over time, I'd like to come back to early projects like this one and potentially add new features that were previously unknown to me. It could also be helpful to any Python beginner who wants to understand the language.
You're free to create a fork and change the code in any way you want. I'd love to see this project in the hands of someone more capable than me.
